import json, re, os, sys

# 1. Update categories.json
cats = json.load(open('data/categories.json'))
countMap = {
    "ai-assistant": 22, "ai-image": 10, "ai-video": 11, "ai-voice-music": 8,
    "ai-code": 6, "ai-workspace": 5, "ai-writing": 7, "bundles": 5
}
for c in cats:
    if c['id'] in countMap:
        c['count'] = countMap[c['id']]
        if c['id'] == 'ai-image': c['from'] = 190
        if c['id'] == 'ai-writing': c['from'] = 390

if not any(c['id'] == 'ai-design' for c in cats):
    cats.append({
        "id": "ai-design", "slug": "ai-design", "displayName": "AI Design & Creative",
        "industrySubtitle": "Canva Pro, Gamma", "icon": "Palette", "from": 190, "count": 2,
        "description": "AI-powered design tools for creatives and businesses. Canva Pro with AI Magic Studio for social media, presentations, and graphics. Gamma for AI presentations. Create stunning visuals without design experience."
    })
json.dump(cats, open('data/categories.json', 'w'), indent=2, ensure_ascii=False)
print("1. categories.json updated")

# 2-3. Update counts across pages
for f in ['src/pages/ProductsPage.tsx', 'src/pages/AboutPage.tsx', 'src/sections/HeroSection.tsx', 'src/components/SEOHead.tsx', 'src/pages/Home.tsx']:
    if os.path.exists(f):
        content = open(f).read()
        orig = content
        content = content.replace('All 57 AI Tools', 'All 76 AI Tools')
        content = content.replace('Browse 57 AI', 'Browse 76 AI')
        content = content.replace('57 premium subscriptions', '76 premium subscriptions')
        content = content.replace('57 tools including', '76 tools including')
        content = content.replace('56 AI', '76 AI')
        content = content.replace('56 tools', '76 tools')
        content = content.replace('56 premium', '76 premium')
        if content != orig:
            open(f, 'w').write(content)
print("2-3. Page counts updated")

# 4. Add routes to App.tsx
app = open('src/App.tsx').read()
new_routes = """      {/* Batch 1 - New Brand Pages */}
      <Route path="/grammarly-premium-bangladesh">{() => <BrandPage brandSlug="grammarly-premium-bangladesh" />}</Route>
      <Route path="/quillbot-premium-bangladesh">{() => <BrandPage brandSlug="quillbot-premium-bangladesh" />}</Route>
      <Route path="/canva-pro-bangladesh">{() => <BrandPage brandSlug="canva-pro-bangladesh" />}</Route>
      <Route path="/microsoft-copilot-pro-bangladesh">{() => <BrandPage brandSlug="microsoft-copilot-pro-bangladesh" />}</Route>
      <Route path="/jasper-ai-bangladesh">{() => <BrandPage brandSlug="jasper-ai-bangladesh" />}</Route>
      <Route path="/adobe-firefly-bangladesh">{() => <BrandPage brandSlug="adobe-firefly-bangladesh" />}</Route>
      <Route path="/pika-labs-bangladesh">{() => <BrandPage brandSlug="pika-labs-bangladesh" />}</Route>
      <Route path="/opus-clip-bangladesh">{() => <BrandPage brandSlug="opus-clip-bangladesh" />}</Route>
      <Route path="/descript-pro-bangladesh">{() => <BrandPage brandSlug="descript-pro-bangladesh" />}</Route>
      <Route path="/murf-ai-bangladesh">{() => <BrandPage brandSlug="murf-ai-bangladesh" />}</Route>

"""
insert = app.find('{/* Brand pages - ChatGPT */}')
if insert > 0 and 'grammarly-premium-bangladesh' not in app:
    app = app[:insert] + new_routes + app[insert:]

if '/ai-design' not in app:
    app = app.replace(
        '<Route path="/ai-writing">{() => <CategoryPage categoryId="ai-writing" />}</Route>',
        '<Route path="/ai-writing">{() => <CategoryPage categoryId="ai-writing" />}</Route>\n      <Route path="/ai-design">{() => <CategoryPage categoryId="ai-design" />}</Route>'
    )
open('src/App.tsx', 'w').write(app)
print("4. App.tsx routes updated")

# 5. Add brand meta entries to BrandPage.tsx
bp = open('src/pages/BrandPage.tsx').read()
if 'grammarly-premium-bangladesh' not in bp:
    # Find the closing of BRAND_META before COMPARE_META
    close_idx = bp.rfind('};', 0, bp.index('const COMPARE_META'))
    new_meta = """
  "grammarly-premium-bangladesh": { displayName: "Grammarly Premium", tagline: "AI writing assistant for perfect English", seoTitle: "Grammarly Premium Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Grammarly Premium price in Bangladesh. AI grammar, spelling, tone and clarity checking. Pay with bKash/Nagad. Instant delivery. 30-day warranty.", description: "Grammarly Premium uses AI to check grammar, spelling, tone, and clarity in real time. Essential for students writing thesis, professionals drafting emails, and content creators polishing copy. Plagiarism checker included.", accentColor: "#14b8a6", filterBySlug: true, faqs: [{ q: "Is Grammarly Premium worth it?", a: "Yes - for anyone writing in English. It catches errors your eyes miss, improves tone, and checks plagiarism. Students see better assignment grades; professionals send polished emails." },{ q: "Does Grammarly work offline?", a: "The browser extension and desktop app work on most sites and apps. Some features require internet connection." },{ q: "Can I use Grammarly on my phone?", a: "Yes - Grammarly keyboard is available for iOS and Android. Premium features work across all devices." },{ q: "What's the difference between Free and Premium?", a: "Free catches basic grammar and spelling. Premium adds tone detection, word choice suggestions, sentence rewrites, plagiarism detection, and advanced clarity improvements." },{ q: "How do I buy Grammarly in Bangladesh?", a: "Message AI Premium Shop on WhatsApp. Pay with bKash or Nagad. Receive your login in 5-30 minutes. No credit card needed." }] },
  "quillbot-premium-bangladesh": { displayName: "QuillBot Premium", tagline: "AI paraphrasing and writing for students", seoTitle: "QuillBot Premium Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "QuillBot Premium price in Bangladesh. AI paraphrasing, summarizing, grammar check, and plagiarism detection. Pay with bKash/Nagad. Instant delivery.", description: "QuillBot Premium is the #1 AI paraphrasing tool for students and researchers. Paraphrase text in multiple modes, summarize articles, check grammar, detect plagiarism, and generate citations. Perfect for Bangladeshi students writing English assignments.", accentColor: "#f59e0b", filterBySlug: true, faqs: [{ q: "What does QuillBot Premium do?", a: "QuillBot Premium offers unlimited paraphrasing in all modes (Standard, Fluency, Creative, Shorten, Expand), faster processing, advanced grammar rewrites, plagiarism checker, and citation generator." },{ q: "Is QuillBot safe for academic work?", a: "Yes when used ethically. QuillBot helps you rephrase and improve your own writing. Never submit paraphrased content as your original work without proper citation." },{ q: "Does QuillBot work with Bengali?", a: "QuillBot works with English text primarily. For Bengali content, it can help with English portions of bilingual documents." },{ q: "Can I use QuillBot on mobile?", a: "Yes - QuillBot works in mobile browsers. There are also Chrome, Edge, and Word extensions." },{ q: "How fast is delivery?", a: "Shared plans: 5-30 minutes after payment. Personal plans: 2-4 hours. Pay via bKash or Nagad." }] },
  "canva-pro-bangladesh": { displayName: "Canva Pro", tagline: "All-in-one AI design tool for creators", seoTitle: "Canva Pro Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Canva Pro price in Bangladesh. AI Magic Studio, 100M+ stock assets, brand kit, background remover. Pay with bKash/Nagad. Instant delivery. 30-day warranty.", description: "Canva Pro is the world's easiest design tool, now supercharged with AI. Magic Studio creates images, edits photos, writes copy, and animates designs. 100 million+ stock photos, videos, and graphics. Brand kit for consistent visuals. Perfect for Bangladeshi social media managers, marketers, and small businesses.", accentColor: "#7c3aed", filterBySlug: true, faqs: [{ q: "What can I do with Canva Pro?", a: "Create social media posts, presentations, logos, flyers, videos, and more. Access 100M+ stock assets, AI image generation, background removal, brand kit, and resize designs instantly for any platform." },{ q: "Is Canva Pro good for beginners?", a: "Absolutely. Canva Pro is designed for non-designers. Drag-and-drop interface, thousands of templates, and AI tools make professional design accessible to everyone." },{ q: "Can I use Canva Pro for commercial projects?", a: "Yes. All Canva Pro content is licensed for commercial use. You can sell designs, use them in client work, and publish them anywhere." },{ q: "Does Canva Pro work offline?", a: "Canva requires internet for full functionality. You can download designs for offline viewing. The mobile app has limited offline capabilities." },{ q: "How do I buy Canva Pro in Bangladesh?", a: "Message AI Premium Shop on WhatsApp (+880 1865-385348). Choose shared or personal. Pay with bKash/Nagad. Receive your access in 5-30 minutes." }] },
  "microsoft-copilot-pro-bangladesh": { displayName: "Microsoft Copilot Pro", tagline: "AI in Word, Excel, PowerPoint and Outlook", seoTitle: "Microsoft Copilot Pro Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Microsoft Copilot Pro price in Bangladesh. AI assistant in Microsoft 365 apps. Pay with bKash/Nagad. Instant delivery. 30-day warranty.", description: "Microsoft Copilot Pro brings GPT-4 powered AI directly into your Microsoft 365 apps. Write emails in Outlook, analyze data in Excel, create slides in PowerPoint, and draft documents in Word - all with AI assistance. Essential for professionals and students in Bangladesh using Microsoft Office.", accentColor: "#2563eb", filterBySlug: true, faqs: [{ q: "What apps does Copilot Pro work with?", a: "Copilot Pro works with Word, Excel, PowerPoint, Outlook, Teams, and OneNote. It also includes the standalone Copilot web app with GPT-4 Turbo." },{ q: "Do I need Microsoft 365 to use Copilot Pro?", a: "Yes, Copilot Pro requires an active Microsoft 365 subscription. The AI features are integrated into the apps, not standalone." },{ q: "Is Copilot Pro different from free Copilot?", a: "Yes. Copilot Pro adds priority access to GPT-4, image creation in Designer, and AI features inside Microsoft 365 apps. Free Copilot is limited to basic web chat." },{ q: "Can students benefit from Copilot Pro?", a: "Absolutely. Copilot Pro helps students write essays, analyze data, create presentations, and summarize research. It's like having a personal tutor in every Office app." },{ q: "How do I buy Copilot Pro in Bangladesh?", a: "Message AI Premium Shop on WhatsApp. Pay with bKash or Nagad. We set up your Microsoft account with Copilot Pro in 5-30 minutes." }] },
  "jasper-ai-bangladesh": { displayName: "Jasper AI", tagline: "AI copywriter for marketing teams", seoTitle: "Jasper AI Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Jasper AI price in Bangladesh. AI marketing copywriter for blogs, ads, and social media. Pay with bKash/Nagad. Instant delivery.", description: "Jasper AI is the leading AI copywriting tool for marketing teams and agencies. Write blog posts, ad copy, email campaigns, and social media content in your brand voice. Built-in SEO optimization and plagiarism checking. Perfect for Bangladeshi digital marketers and content agencies.", accentColor: "#ec4899", filterBySlug: true, faqs: [{ q: "What content can Jasper AI create?", a: "Jasper AI writes blog posts, social media captions, ad copy, email sequences, product descriptions, website copy, and more. It maintains your brand voice across all content." },{ q: "Is Jasper better than ChatGPT for marketing?", a: "Jasper is specialized for marketing with built-in templates, brand voice training, SEO optimization, and team collaboration. ChatGPT is more general-purpose. Many marketers use both." },{ q: "Can Jasper write in Bengali?", a: "Jasper primarily works in English. For Bengali content marketing, pair Jasper for English campaigns with human translation for Bangla audiences." },{ q: "Does Jasper check for plagiarism?", a: "Yes, Jasper includes a built-in plagiarism checker powered by Copyscape. Every piece of content is scanned before delivery." },{ q: "How do I buy Jasper AI in Bangladesh?", a: "Message AI Premium Shop on WhatsApp (+880 1865-385348). Pay with bKash or Nagad. Receive your account in 5-30 minutes for shared, 2-4 hours for personal." }] },
  "adobe-firefly-bangladesh": { displayName: "Adobe Firefly", tagline: "Safe AI image generation from Adobe", seoTitle: "Adobe Firefly Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Adobe Firefly price in Bangladesh. AI image generation, generative fill, text effects. Commercial-safe. Pay with bKash/Nagad. Instant delivery.", description: "Adobe Firefly is the only commercially safe AI image generator trained on Adobe Stock and public domain content. Create images, extend backgrounds, remove objects, and apply text effects - all from within Photoshop and Express. Perfect for Bangladeshi designers and photographers who need worry-free commercial use.", accentColor: "#f97316", filterBySlug: true, faqs: [{ q: "Is Adobe Firefly free to use?", a: "Firefly offers 25 free generative credits per month. For unlimited creation, Firefly Premium provides 100+ monthly credits with full access to all generative features." },{ q: "Are Firefly images safe for commercial use?", a: "Yes. Adobe Firefly is trained on Adobe Stock and public domain content, not random web scraping. Generated images come with a commercial use license - no legal worries." },{ q: "Does Firefly work inside Photoshop?", a: "Yes. Firefly generative features are built into Photoshop (beta), Lightroom, and Adobe Express. You don't need separate software." },{ q: "How many images can I generate?", a: "Free tier: 25 credits/month. Premium: 100+ credits. One image generation typically uses 1 credit. Complex edits may use more." },{ q: "How do I buy Firefly Premium in Bangladesh?", a: "Message AI Premium Shop on WhatsApp. Pay with bKash or Nagad. We activate Firefly Premium on your Adobe account in 5-30 minutes." }] },
  "pika-labs-bangladesh": { displayName: "Pika Labs", tagline: "Text-to-video AI for creators", seoTitle: "Pika Labs Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Pika Labs price in Bangladesh. Text-to-video AI generation. Pay with bKash/Nagad. Instant delivery.", description: "Pika Labs turns your text prompts into cinematic videos. Create AI-generated footage for TikTok, Reels, and Shorts. Simple interface, fast generation, stunning results. A great budget alternative to Runway for Bangladeshi creators experimenting with AI video.", accentColor: "#22c55e", filterBySlug: true, faqs: [{ q: "What can Pika Labs create?", a: "Pika Labs generates short videos (3-5 seconds) from text prompts. Great for social media clips, concept art animation, and creative experiments. Not for long-form video production." },{ q: "How does Pika compare to Runway?", a: "Pika is simpler and cheaper, focused on quick social clips. Runway offers more advanced editing, longer videos, and professional controls. Many creators use both." },{ q: "Can I use Pika videos commercially?", a: "Pika videos can be used commercially according to their terms. Always review the latest usage rights on pika.art." },{ q: "Does Pika support image-to-video?", a: "Yes. Upload an image and Pika will animate it into a short video clip. Great for bringing static designs to life." },{ q: "How do I buy Pika Labs in Bangladesh?", a: "Message AI Premium Shop on WhatsApp (+880 1865-385348). Pay with bKash or Nagad. Shared access available in 5-30 minutes." }] },
  "opus-clip-bangladesh": { displayName: "Opus Clip", tagline: "Turn long videos into viral Shorts", seoTitle: "Opus Clip Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Opus Clip price in Bangladesh. AI video repurposing for Shorts, Reels, and TikTok. Pay with bKash/Nagad. Instant delivery.", description: "Opus Clip uses AI to automatically transform your long videos into dozens of viral Shorts, Reels, and TikTok clips. It finds the best moments, adds auto-captions, and creates engaging hooks. Essential for Bangladeshi YouTubers, podcasters, and coaches who want to maximize content reach.", accentColor: "#8b5cf6", filterBySlug: true, faqs: [{ q: "How does Opus Clip work?", a: "Upload a long video (podcast, interview, webinar). Opus Clip's AI identifies the best moments, creates multiple short clips with auto-captions, and scores each clip's viral potential." },{ q: "What platforms does Opus Clip support?", a: "Opus Clip creates content optimized for YouTube Shorts, Instagram Reels, TikTok, and LinkedIn. One long video becomes 10-30 short clips." },{ q: "Does Opus Clip add captions?", a: "Yes - Opus Clip auto-generates captions with 97%+ accuracy. Captions are customizable with your brand colors and fonts." },{ q: "Can I edit the clips Opus creates?", a: "Yes. Opus Clip provides an editor where you can trim, adjust captions, change layouts, and refine each clip before publishing." },{ q: "How do I buy Opus Clip in Bangladesh?", a: "Message AI Premium Shop on WhatsApp. Pay with bKash or Nagad. Shared plans available in 5-30 minutes. Personal plans in 2-4 hours." }] },
  "descript-pro-bangladesh": { displayName: "Descript Pro", tagline: "Edit video by editing text", seoTitle: "Descript Pro Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Descript Pro price in Bangladesh. AI video and podcast editing. Pay with bKash/Nagad. Instant delivery.", description: "Descript Pro revolutionizes video and podcast editing by letting you edit the transcript like a Word document. Delete words from the text, and they disappear from the video. Auto-transcription, AI overdub voice cloning, and screen recording. Perfect for Bangladeshi podcasters, educators, and content creators.", accentColor: "#06b6d4", filterBySlug: true, faqs: [{ q: "How does text-based video editing work?", a: "Descript transcribes your video, then you edit the text. Delete a sentence in the transcript, and it disappears from the video. Move a paragraph, and the video reorders. No timeline scrubbing needed." },{ q: "What is Overdub voice cloning?", a: "Overdub lets you type new sentences and Descript synthesizes them in your own voice. Fix mistakes, add new content, or translate - all without re-recording." },{ q: "Is Descript good for podcasts?", a: "Extremely. Descript was built for podcasters. Multi-track editing, filler word removal (um, uh), auto-leveling, and one-click publishing to all platforms." },{ q: "Can I use Descript for screen recording?", a: "Yes. Descript includes a built-in screen recorder with automatic transcription. Record tutorials, demos, and presentations - then edit instantly." },{ q: "How do I buy Descript Pro in Bangladesh?", a: "Message AI Premium Shop on WhatsApp (+880 1865-385348). Pay with bKash or Nagad. Shared plans: 5-30 min. Personal plans: 2-4 hours." }] },
  "murf-ai-bangladesh": { displayName: "Murf AI", tagline: "Studio-quality AI voiceovers", seoTitle: "Murf AI Bangladesh - Price in BDT | AI Premium Shop", seoDescription: "Murf AI price in Bangladesh. 120+ AI voices in 20+ languages. Text-to-speech studio. Pay with bKash/Nagad. Instant delivery.", description: "Murf AI transforms text into studio-quality voiceovers using 120+ realistic AI voices across 20+ languages. Perfect for Bangladeshi video creators, e-learning developers, and marketers who need professional narration without hiring voice actors. Includes voice cloning for brand consistency.", accentColor: "#14b8a6", filterBySlug: true, faqs: [{ q: "How realistic are Murf AI voices?", a: "Murf AI voices are among the most natural-sounding in the industry. Many listeners cannot distinguish Murf voices from human narration. Perfect for YouTube, ads, and e-learning." },{ q: "Does Murf support Bengali?", a: "Murf supports English, Hindi, and many other languages. While full Bengali support is limited, English voiceovers with Bangla-accented options are available. Check murf.ai for the latest language list." },{ q: "Can I clone my own voice?", a: "Yes - Murf Studio plan includes voice cloning. Record a short sample and Murf creates an AI version of your voice for unlimited use." },{ q: "What audio formats does Murf export?", a: "Murf exports MP3, WAV, and FLAC. All formats are studio-quality and ready for YouTube, podcasts, ads, and professional video production." },{ q: "How do I buy Murf AI in Bangladesh?", a: "Message AI Premium Shop on WhatsApp (+880 1865-385348). Pay with bKash or Nagad. Shared access in 5-30 minutes. Personal access in 2-4 hours." }] },"""
    bp = bp[:close_idx] + ',' + new_meta + bp[close_idx:]
    open('src/pages/BrandPage.tsx', 'w').write(bp)
    print("5. BrandPage.tsx meta entries added")

print("\nAll Batch 1 system updates complete!")
